CREATE TABLE SALA (
    ID_SALA NUMBER(10) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    TIPO VARCHAR2(10) NOT NULL,
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    PRIMARY KEY (ID_SALA)
);

CREATE TABLE USUARIO (
    ID_USUARIO NUMBER(10) NOT NULL,
    NOME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    DATA_CADASTRO DATE DEFAULT SYSDATE,
    SENHA VARCHAR2(20) NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE BLOQUEIO(
    ID_USU_BLOQUEIA NUMBER(10) NOT NULL,
    ID_USU_BLOQUEADO NUMBER(10) NOT NULL,
    DATA_BLOQUEIO DATE DEFAULT SYSDATE,
    PRIMARY KEY (ID_USU_BLOQUEIA, ID_USU_BLOQUEADO),
    FOREIGN KEY (ID_USU_BLOQUEIA) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_USU_BLOQUEADO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE MENSAGEM_USUARIO (
    ID_MENSAGEM NUMBER(10) NOT NULL,
    ID_REMETENTE NUMBER(10) NOT NULL,
    ID_DESTINATARIO NUMBER(10) NOT NULL,
    DATA_ENVIO DATE DEFAULT SYSDATE,
    MENSAGEM VARCHAR2(500) NOT NULL,
    PRIMARY KEY (ID_MENSAGEM),
    FOREIGN KEY (ID_REMETENTE) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_DESTINATARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PARTICIPACAO_SALA (
    ID_USUARIO NUMBER(10) NOT NULL,
    ID_SALA NUMBER(10) NOT NULL,
    DATA_ENTRADA DATE DEFAULT SYSDATE,
    PRIMARY KEY (ID_USUARIO, ID_SALA),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA)
);

CREATE TABLE MENSAGEM_SALA (
    ID_MENSAGEM NUMBER(10) NOT NULL,
    ID_SALA NUMBER(10) NOT NULL,
    ID_REMETENTE NUMBER(10) NOT NULL,
    DATA_ENVIO DATE DEFAULT SYSDATE,
    MENSAGEM VARCHAR2(500) NOT NULL,
    PRIMARY KEY (ID_MENSAGEM),
    FOREIGN KEY (ID_SALA) REFERENCES SALA(ID_SALA),
    FOREIGN KEY (ID_REMETENTE) REFERENCES USUARIO(ID_USUARIO)
);

ALTER TABLE SALA ADD CRIADOR NUMBER(10) NOT NULL;
ALTER TABLE SALA ADD CONSTRAINT FK_CRIADOR FOREIGN KEY (CRIADOR) REFERENCES USUARIO(ID_USUARIO);